// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPINoleggi.Data;

#nullable disable

namespace RestAPINoleggi.Migrations
{
    [DbContext(typeof(NoleggiContext))]
    [Migration("20220315133518_AMigration")]
    partial class AMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Noleggio_Library.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("Noleggio_Library.Noleggio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurataNoleggio")
                        .HasColumnType("int");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Noleggi");
                });

            modelBuilder.Entity("Noleggio_Library.Veicolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("CostoVeicolo")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modello")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TariffaGiornaliera")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Id");

                    b.ToTable("Veicolo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Veicolo");
                });

            modelBuilder.Entity("Noleggio_Library.Automobile", b =>
                {
                    b.HasBaseType("Noleggio_Library.Veicolo");

                    b.Property<int>("NumeroPosti")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Automobile");
                });

            modelBuilder.Entity("Noleggio_Library.Furgone", b =>
                {
                    b.HasBaseType("Noleggio_Library.Veicolo");

                    b.Property<double>("Capacita")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Furgone");
                });

            modelBuilder.Entity("Noleggio_Library.Noleggio", b =>
                {
                    b.HasOne("Noleggio_Library.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noleggio_Library.Veicolo", "Veicolo")
                        .WithMany()
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veicolo");
                });
#pragma warning restore 612, 618
        }
    }
}
